=== ASDF-AMARKER/LMSGI_DTD/cotalogo/catalogo.dtd
<!ELEMENT catalog (llista_actors, llista_pelicules, llista_recomanacions_pelicules)>

<!ELEMENT llista_actors (actor+)>
<!ELEMENT actor (nom, edat?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT edat (#PCDATA)>
<!ATTLIST actor id ID #REQUIRED>

<!ELEMENT llista_pelicules (pelicula+)>
<!ELEMENT pelicula (titol, director, any, actors, entrada)>
<!ATTLIST pelicula id ID #REQUIRED>
<!ELEMENT titol (#PCDATA)>
<!ATTLIST titol idioma CDATA #REQUIRED>
<!ELEMENT director (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT actors (actor_ref+)>
<!ELEMENT actor_ref EMPTY>

<!ATTLIST actor_ref ref IDREF #REQUIRED>
<!ELEMENT entrada (#PCDATA)>
<!ATTLIST entrada gratuita (si | no) "si">

<!ELEMENT llista_recomanacions_pelicules (recomanacio*)>
<!ELEMENT recomanacio EMPTY>

<!ATTLIST recomanacio ref IDREF #REQUIRED>

=== ASDF-AMARKER/LMSGI_DTD/cotalogo/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalogo.dtd">
<catalog>
    <llista_actors>
        <actor id="actor1">
            <nom>John Doe</nom>
            <edat>30</edat>
        </actor>
        <actor id="actor2">
            <nom>Jane Smith</nom>
        </actor>
        <actor id="actor3">
            <nom>Bob Johnson</nom>
            <edat>45</edat>
        </actor>
    </llista_actors>
    
    <llista_pelicules>
        <pelicula id="pelicula1">
            <titol idioma="es">El Gran Robo</titol>
            <director>Steven Spielberg</director>
            <any>1993</any>
            <actors>
                <actor_ref ref="actor1"/>
                <actor_ref ref="actor2"/>
            </actors>
            <entrada gratuita="si">0,0</entrada>
        </pelicula>
        <pelicula id="pelicula2">
            <titol idioma="en">The Matrix</titol>
            <director>Wachowski Sisters</director>
            <any>1999</any>
            <actors>
                <actor_ref ref="actor2"/>
                <actor_ref ref="actor3"/>
            </actors>
            <entrada gratuita="no">16,5</entrada> 
        </pelicula>
    </llista_pelicules>
    
    <llista_recomanacions_pelicules>
        <recomanacio ref="pelicula1"/>
        <recomanacio ref="pelicula2"/>
    </llista_recomanacions_pelicules>
</catalog>
